### ISSUE TITLE
Panics on using virtual manifest (workspace)

### ISSUE THREAD

**Issue by MerlinDE** [phil-opp/cargo-post#7]
Running **cargo post** on a multi-package project tied together with a virtual manifest (a Cargo.toml with only [workspace] and members definitions in parent directory) panics with `'Please specify a --package argument'`.

To reproduce
```sh
mkdir dummy
cd dummy
cargo new mine
cargo new --lib mylib
```

add the following `Cargo.toml` to `dummy` dir

```rust
[workspace]
members = ["mine","mylib"]
```

add the following to `mine/Cargo.toml`

```rust
[dependencies]
mylib = { path = "../mylib" }
```

run
```sh
cargo post --package mine
```

results in
```
thread 'main' panicked at 'Please specify a `--package` argument', /Users/<USERNAME>/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-post-0.1.3/src/main.rs:109:17
```

I've tried this on both `stable` and `nightly`.

It does work when you remove `dummy/Cargo.toml`, add `[workspace]`without any members definition to `mine/Cargo.toml` and run cargo from mine subdirectory. In that case there's obviously no need for the `--package` parameter.

**Comment by phil-opp** [comment]
Thanks for reporting! I opened #8 with a fix.
